<script src="/front/assets/js/bootstrap/bootstrap.bundle.min.js"></script><!-- iconsax js -->
<script src="/front/assets/js/iconsax.js"> </script><!-- cursor js-->
<script src="/front/assets/js/stats.min.js"> </script>
<script src="/front/assets/js/cursor.js"> </script>
<script src="/front/assets/js/swiper-slider/swiper-bundle.min.js"></script>
<script src="/front/assets/js/swiper-slider/swiper-custom.js"></script>
<script src="/front/assets/js/countdown.js"></script>
<script src="/front/assets/js/newsletter.js"></script>
<script src="/front/assets/js/skeleton-loader.js"></script><!-- touchspin-->
<script src="/front/assets/js/touchspin.js"></script><!-- cookie js-->
<script src="/front/assets/js/cookie.js"></script><!-- tost js -->
<script src="/front/assets/js/toastify.js"></script>
<script src="/front/assets/js/theme-setting.js"></script><!-- Theme js-->
<script src="/front/assets/js/script.js"></script>